services: docker

env:
  - distro=debian8 node_version=8
  - distro=debian8 node_version=9
  - distro=debian9 node_version=8
  - distro=debian9 node_version=9
  - distro=ubuntu1604 node_version=8
  - distro=ubuntu1604 node_version=9

install:
  - export container_id=$(date +%s)
  - idempotence=$(mktemp)
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  # Build and run docker container
  - docker pull geerlingguy/docker-$distro-ansible:latest
  - docker run --detach --volume="$(dirname "$TRAVIS_BUILD_DIR")":/etc/ansible/roles:rw --name $container_id --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro geerlingguy/docker-$distro-ansible:latest /lib/systemd/systemd
  - docker exec --tty ${container_id} apt-get update -qq
  - docker ps

script:
  - docker exec --tty ${container_id} ansible-playbook /etc/ansible/roles/ansible-role-node/tests/test.yml --syntax-check
  - docker exec ${container_id} env ANSIBLE_FORCE_COLOR=1 ansible-playbook /etc/ansible/roles/ansible-role-node/tests/test.yml --extra-vars="version=${node_version}" -vvv
  - docker exec ${container_id} ansible-playbook /etc/ansible/roles/ansible-role-node/tests/test.yml --extra-vars="version=${node_version}" | tee -a $idempotence
  - tail $idempotence | grep -q 'changed=0.*failed=0' && (printf 'Idempotence test pass') || (printf 'Idempotence test fail' && exit 1)

  - docker exec --tty ${container_id} node --version | grep "v${node_version}"